### ISSUE TITLE
[bug] Invalid regular expression: /(?:(?:^\.)|(?:[/\]\.))[^/\.].*/: Unterminated group

### ISSUE THREAD

**Issue by Aladdin-ADD** [BrainMaestro/eslint-plugin-optimize-regex#9] opened 2017-07-30 22:45 UTC
```diff
-const globIncludesDotfiles = /(?:(?:^\.)|(?:[/\\]\.))[^/\\.].*/.test(pattern);
+const globIncludesDotfiles = /(?:(?:^\.)|(?:[/\]\.))[^/\.].*/.test(pattern);

```

**Comment by BrainMaestro** [comment] 2017-07-31 11:04
Duplicate of #8

**Closed by BrainMaestro** 2017-07-31 11:04 UTC
